WN_BUILD_HELPER_ROOT:=../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../../
WN_LIBRARIES:= WNScripting WNFileSystem WNEntryPoint
WN_SOURCES := ../../src/Main.cpp
WN_ADDITIONAL_CFLAGS := -std=c++11

include $(WN_BUILD_HELPER_ROOT)Makefile
