WN_BUILD_HELPER_ROOT:=../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../
WN_LIBRARIES:= WNScripting WNFileSystem WNEntryPoint
WN_SOURCES := ../../src/Main.cpp
WN_ADDITIONAL_CFLAGS := -std=c++11
WN_ADDITIONAL_LDFLAGS := -latomic

include $(WN_BUILD_HELPER_ROOT)Makefile
