include ../../PreLibrariesHelper.mk

LIB            := WNGraphics
SOURCES        := WNGraphicsDeviceFactory.cpp \
                  GLX/WNGraphicsDeviceGLX.cpp
ADDITIONALLIBS := $(ADDITIONALLIBS)

include ../../LibrariesHelper.mk
