WN_BUILD_HELPER_ROOT := ../../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH := ../../../../../
WN_LIBRARIES := WNEntryPoint
PROJECT_NAME := WNConcurrencyTest
PROGRAM_NAME := WNConcurrencyTest
LIB_NAME := WNConcurrencyTest
ACTIVITY_NAME := WNConcurrencyTest
PACKAGE_NAME := org.WNProject.WNConcurrencyTest
WN_SOURCES := ../../src/Main.cpp \
			  ../../src/Tests/WNMutexTests.cpp \
			  ../../src/Tests/WNSemaphoreTests.cpp \			  
			  ../../src/Tests/WNThreadTests.cpp \
			  ../../src/Tests/WNThreadPoolTests.cpp
WN_ADDITIONAL_ANDROID_LIBS := android_native_app_glue googletest_static
WN_ADDITIONAL_ANDROID_MODULES := android/native_app_glue third_party/googletest

include $(WN_BUILD_HELPER_ROOT)Makefile