WN_BUILD_HELPER_ROOT:=../../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../../../
WN_LIBRARIES:=gtest WNEntryPoint
PROJECT_NAME := WNConcurrencyTest
PROGRAM_NAME := WNConcurrencyTest
LIB_NAME := WNConcurrencyTest
ACTIVITY_NAME := WNConcurrencyTest
PACKAGE_NAME := org.WNProject.WNConcurrencyTest
WN_SOURCES := ../../src/Main.cpp \
			  ../../src/Tests/WNAtomicTests.cpp \
			  ../../src/Tests/WNThreadTests.cpp \
			  ../../src/Tests/WNThreadPoolTests.cpp

include $(WN_BUILD_HELPER_ROOT)Makefile
