version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
    allow:
      - dependency-name: googletest
      - dependency-name: xxhash
