WN_BUILD_HELPER_ROOT:=../../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../../
WN_LIBRARIES:=WNEntryPoint WNPlatform
PROJECT_NAME :=WNPlatformTest
PROGRAM_NAME :=WNPlatformTest
LIB_NAME := WNPlatformTest
ACTIVITY_NAME :=WNPlatformTest
WN_SOURCES := ../../src/Main.cpp \
			  ../../src/Tests/WNSurfaceTests.cpp \
			  ../../src/Tests/WNSystemTests.cpp \
			  ../../src/Tests/WNTimeTests.cpp
WN_ADDITIONAL_ANDROID_LIBS:=android_native_app_glue googletest_static
WN_ADDITIONAL_ANDROID_MODULES:=android/native_app_glue third_party/googletest

include $(WN_BUILD_HELPER_ROOT)Makefile
