WN_BUILD_HELPER_ROOT:=../../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../../../
WN_LIBRARIES:=gtest WNEntryPoint WNPlatform
PROJECT_NAME :=WNPlatformTest
PROGRAM_NAME :=WNPlatformTest
LIB_NAME := WNPlatformTest
ACTIVITY_NAME :=WNPlatformTest
WN_SOURCES := ../../src/Main.cpp \
			  ../../src/Tests/WNSurfaceTests.cpp \
			  ../../src/Tests/WNSystemTests.cpp \
			  ../../src/Tests/WNTimeTests.cpp
include $(WN_BUILD_HELPER_ROOT)Makefile
