WN_BUILD_HELPER_ROOT:=../../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../../
WN_SOURCES :=Main.cpp WNAbsTests.cpp WNBounds2ConstructorTests.cpp WNBounds3ConstructorTests.cpp WNCeilTests.cpp WNFloorTests.cpp WNInvSqrtTests.cpp WNMatrix2CreateIdentityTests.cpp \
			 WNMatrix2CreateZeroTests.cpp WNMatrix2IdentityTests.cpp WNMatrix2ZeroTests.cpp WNMatrix3CreateIdentityTests.cpp WNMatrix3CreateZeroTests.cpp WNMatrix3IdentityTests.cpp \
			 WNMatrix3ZeroTests.cpp WNMatrix4CreateIdentityTests.cpp WNMatrix4CreateZeroTests.cpp WNMatrix4IdentityTests.cpp WNMatrix4ZeroTests.cpp WNMatrixXCreateIdentityTests.cpp \
			 WNMatrixXCreateZeroTests.cpp WNMatrixXIdentityTests.cpp WNMatrixXZeroTests.cpp WNRoundTests.cpp WNSqrtTests.cpp WNTruncTests.cpp WNVector2AddAssignTests.cpp \
			 WNVector2AddAssignVectorTests.cpp WNVector2AddTests.cpp WNVector2ArraySubscriptTests.cpp WNVector2AverageTests.cpp WNVector2ClampTests.cpp WNVector2ConstructorTests.cpp \
			 WNVector2ConvertToTests.cpp WNVector2CreateZeroTests.cpp WNVector2DivideAssignTests.cpp WNVector2DivideAssignVectorTests.cpp WNVector2DivideTests.cpp WNVector2DotTests.cpp \
			 WNVector2FuntionCallTests.cpp WNVector2GetNormalizedTests.cpp WNVector2LengthSquaredTests.cpp WNVector2LengthTests.cpp WNVector2MultiplyAddTests.cpp \
			 WNVector2MultiplyAddVectorTests.cpp WNVector2MultiplyAssignTests.cpp WNVector2MultiplyAssignVectorTests.cpp WNVector2MultiplySubtractTests.cpp \
			 WNVector2MultiplySubtractVectorTests.cpp WNVector2MultiplyTests.cpp WNVector2NormalizeTests.cpp WNVector2OneTests.cpp WNVector2RecipricolTests.cpp \
			 WNVector2SubtractAssignTests.cpp WNVector2SubtractAssignVectorTests.cpp WNVector2SubtractTests.cpp WNVector2ZeroTests.cpp WNVector3AddAssignTests.cpp \
			 WNVector3AddAssignVectorTests.cpp WNVector3AddTests.cpp WNVector3ArraySubscriptTests.cpp WNVector3AverageTests.cpp WNVector3ClampTests.cpp WNVector3ConstructorTests.cpp \
			 WNVector3ConvertToTests.cpp WNVector3CreateZeroTests.cpp WNVector3DivideAssignTests.cpp WNVector3DivideAssignVectorTests.cpp WNVector3DivideTests.cpp WNVector3DotTests.cpp \
			 WNVector3FuntionCallTests.cpp WNVector3GetNormalizedTests.cpp WNVector3LengthSquaredTests.cpp WNVector3LengthTests.cpp WNVector3MultiplyAddTests.cpp \
			 WNVector3MultiplyAddVectorTests.cpp WNVector3MultiplyAssignTests.cpp WNVector3MultiplyAssignVectorTests.cpp WNVector3MultiplySubtractTests.cpp \
			 WNVector3MultiplySubtractVectorTests.cpp WNVector3MultiplyTests.cpp WNVector3NormalizeTests.cpp WNVector3OneTests.cpp WNVector3RecipricolTests.cpp \
			 WNVector3SubtractAssignTests.cpp WNVector3SubtractAssignVectorTests.cpp WNVector3SubtractTests.cpp WNVector3ZeroTests.cpp WNVector4AddAssignTests.cpp \
			 WNVector4AddAssignVectorTests.cpp WNVector4AddTests.cpp WNVector4ArraySubscriptTests.cpp WNVector4AverageTests.cpp WNVector4ClampTests.cpp WNVector4ConstructorTests.cpp \
			 WNVector4ConvertToTests.cpp WNVector4CreateZeroTests.cpp WNVector4DivideAssignTests.cpp WNVector4DivideAssignVectorTests.cpp WNVector4DivideTests.cpp WNVector4DotTests.cpp \
			 WNVector4FuntionCallTests.cpp WNVector4GetNormalizedTests.cpp WNVector4LengthSquaredTests.cpp WNVector4LengthTests.cpp WNVector4MultiplyAddTests.cpp \
			 WNVector4MultiplyAddVectorTests.cpp WNVector4MultiplyAssignTests.cpp WNVector4MultiplyAssignVectorTests.cpp WNVector4MultiplySubtractTests.cpp \
			 WNVector4MultiplySubtractVectorTests.cpp WNVector4MultiplyTests.cpp WNVector4NormalizeTests.cpp WNVector4OneTests.cpp WNVector4RecipricolTests.cpp \
			 WNVector4SubtractAssignTests.cpp WNVector4SubtractAssignVectorTests.cpp WNVector4SubtractTests.cpp WNVector4ZeroTests.cpp WNVectorXAddAssignTests.cpp \
			 WNVectorXAddAssignVectorTests.cpp WNVectorXAddTests.cpp WNVectorXArraySubscriptTests.cpp WNVectorXConstructorTests.cpp WNVectorXConvertToTests.cpp \
			 WNVectorXCreateZeroTests.cpp WNVectorXDivideAssignTests.cpp WNVectorXDivideAssignVectorTests.cpp WNVectorXDivideTests.cpp WNVectorXDotTests.cpp WNVectorXFuntionCallTests.cpp \
			 WNVectorXGetNormalizedTests.cpp WNVectorXLengthSquaredTests.cpp WNVectorXLengthTests.cpp WNVectorXMultiplyAddTests.cpp WNVectorXMultiplyAddVectorTests.cpp \
			 WNVectorXMultiplyAssignTests.cpp WNVectorXMultiplyAssignVectorTests.cpp WNVectorXMultiplySubtractTests.cpp WNVectorXMultiplySubtractVectorTests.cpp WNVectorXMultiplyTests.cpp \
			 WNVectorXNormalizeTests.cpp WNVectorXOneTests.cpp WNVectorXSubtractAssignTests.cpp WNVectorXSubtractAssignVectorTests.cpp WNVectorXSubtractTests.cpp WNVectorXZeroTests.cpp
WN_LIBRARIES:=WNEntryPoint
PROJECT_NAME:= WNMathTest
PROGRAM_NAME:= WNMathTest
LIB_NAME:=WNMathTest
ACTIVITY_NAME:=WNMathTest
PACKAGE_NAME:=org.WNProject.WNMathTest
WN_ADDITIONAL_ANDROID_LIBS:=android_native_app_glue googletest_static
WN_ADDITIONAL_ANDROID_MODULES:=android/native_app_glue third_party/googletest
WN_SOURCES:=$(addprefix ../../src/,$(WN_SOURCES)) 
include $(WN_BUILD_HELPER_ROOT)Makefile
