include ../../../PreTestsHelper.mk

PROJECT   := WNMath
WNLIBS    := WNEntryPoint WNUtils
SOURCES   := Main.cpp WNBasicTests.cpp WNMatrix2Tests.cpp WNMatrix3Tests.cpp WNMatrix4Tests.cpp \
	     WNMatrixTests.cpp WNSphereTests.cpp WNVector2Tests.cpp WNVector3Tests.cpp \
	     WNVector4Tests.cpp WNVectorTests.cpp
PCHFILES  := Common.h

include ../../../TestsHelper.mk
