include ../../../PreTestsHelper.mk

PROJECT	  := WNContainers
SOURCES   := Main.cpp \
             Tests/WNAutoCleanerTests.cpp \
             Tests/WNAllocatorTests.cpp \
             Tests/WNDynamicArrayTests.cpp \
             Tests/WNDequeTests.cpp
WNLIBS    := WNEntryPoint WNUtils
PCHFILES  := Common.h

include ../../../TestsHelper.mk
