include ../../../PreTestsHelper.mk

PROJECT	  := WNContainers
SOURCES   := Main.cpp \
             Tests/WNAutoCleanerTests.cpp
WNLIBS    := WNEntryPoint WNUtils
PCHFILES  := Common.h

include ../../../TestsHelper.mk
