include ../../PreLibrariesHelper.mk

LIB            := WNNetworking
SOURCES        := WNBufferResource.cpp \
                  WNNetworkReadBuffer.cpp \
                  WNNetworkWriteBuffer.cpp \
                  WNNetworkFactory.cpp \
                  WNNetworkManager.cpp \
                  WNConnectionGroup.cpp \
                  WNConnection.cpp \
                  Linux/WNNetworkManagerLinux.cpp \
                  Linux/WNConnectionLinux.cpp \
                  Linux/WNListenConnectionLinux.cpp \
                  Linux/WNInConnectionLinux.cpp \
                  Linux/WNOutConnectionLinux.cpp		  
ADDITIONALLIBS := $(ADDITIONALLIBS)

include ../../LibrariesHelper.mk
