SHELL=/bin/sh
CXX?=g++
AR?=ar
INCLUDES := $(INCLUDES) -I. -I../../.. 
TARGET ?= Release
SOURCEDIR=../src/
OBJDIR = ../build/
WNLIBDIR = ../../../bin/$(TARGET)/
BINDIR ?= ../../../bin/
PCHDIR = ../build/
INCDIR = ../inc/
DEPENDENCYDIR ?= ../../../../Dependencies/Linux/$(shell uname -m)/$(TARGET)
