WN_BUILD_HELPER_ROOT:=../../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../../../
WN_LIBRARIES:=WNEntryPoint WNNetworking
WN_SOURCES := ../../src/Main.cpp
WN_ADDITIONAL_CFLAGS := -std=c++11
PROJECT_NAME := WNNetworkingTest
PROGRAM_NAME := WNNetworkingTest
LIB_NAME := WNNetworkingTest
ACTIVITY_NAME := WNNetworkingTest
PACKAGE_NAME := org.WNProject.WNNetworkingTest


include $(WN_BUILD_HELPER_ROOT)Makefile
