cmake_parse_arguments(
    PARSED_ARGS
    "SYSTEMS_TEST"
    "TEST_NAME;RUN_WRAPPER;TEST_PREFIX"
    "SOURCES;ADDITIONAL_INCLUDES;LIBS"
    ${ARGN})

set_property(TARGET ${PARSED_ARGS_TEST_NAME}_test
  PROPERTY FOLDER "Tests/${PARSED_ARGS_TEST_PREFIX}")
