set_source_groups()
if (${name}_OVERLAY_DISABLED_SOURCES)
  foreach(source in ${${name}_OVERLAY_DISABLED_SOURCES})
    if (EXISTS ${source})
      list(APPEND ${name}_OVERLAY_SOURCES ${source})
    endif()
  endforeach()
endif()