include ../../../PreTestsHelper.mk

PROJECT   := WNGraphics
SOURCES   := Main.cpp 
WNLIBS    := WNGraphics WNPlatform WNEntryPoint WNUtils
ADDITIONALLIBS := -lGL -lX11 -lpthread

include ../../../TestsHelper.mk

