include ../../../PreTestsHelper.mk

PROJECT   := WNCore
PCHFILES  := Common.h
TOOL      := WNCoreTests
SOURCES   := Main.cpp \
             Tests/WNTypesTests.cpp
WNLIBS	  := WNEntryPoint WNUtils

include ../../../TestsHelper.mk

