include ../../../PreTestsHelper.mk

PROJECT   := WNCore
PCHFILES  := Common.h
TOOL      := WNCoreTests
SOURCES   := Main.cpp \
             Tests/WNAlgorithmTests.cpp \
             Tests/WNExtendedTypesTests.cpp \
             Tests/WNTypeTraitsTests.cpp \
             Tests/WNUtilityTests.cpp
WNLIBS	  := WNEntryPoint WNUtils

include ../../../TestsHelper.mk

