include ../../PreLibrariesHelper.mk

LIB            := WNFileSystem
SOURCES        := WNFile.cpp WNFileBuffer.cpp WNReadFileBuffer.cpp WNWriteFileBuffer.cpp
ADDITIONALLIBS := $(ADDITIONALLIBS)

include ../../LibrariesHelper.mk
