WN_BUILD_HELPER_ROOT:=../../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../../
PROJECT_NAME := WNContainerTest
PROGRAM_NAME := WNContainerTest
LIB_NAME := WNContainerTest
ACTIVITY_NAME := WNContainerTest
PACKAGE_NAME := org.WNProject.WNContainerTest
WN_LIBRARIES:=WNEntryPoint
WN_SOURCES := ../../src/Main.cpp\
			  ../../src/Tests/WNAutoCleanerTests.cpp

WN_ADDITIONAL_ANDROID_LIBS:= android_native_app_glue googletest_static
WN_ADDITIONAL_ANDROID_MODULES:= android/native_app_glue third_party/googletest
include $(WN_BUILD_HELPER_ROOT)Makefile
