WN_BUILD_HELPER_ROOT:=../../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../../../
PROJECT_NAME := WNContainerTest
PROGRAM_NAME := WNContainerTest
LIB_NAME := WNContainerTest
ACTIVITY_NAME := WNContainerTest
PACKAGE_NAME := org.WNProject.WNContainerTest
WN_LIBRARIES:=gtest WNEntryPoint
WN_SOURCES := ../../src/Main.cpp\
			  ../../src/Tests/WNAutoCleanerTests.cpp

include $(WN_BUILD_HELPER_ROOT)Makefile
