include ../../PreLibrariesHelper.mk

LIB            := WNPlatform
SOURCES        := WNPlatformFactory.cpp \
                  XWindows/WNSurfaceXWindows.cpp \
                  XWindows/WNSurfaceManagerXWindows.cpp
ADDITIONALLIBS := $(ADDITIONALLIBS)

include ../../LibrariesHelper.mk
