include ../../PreLibrariesHelper.mk

LIB            := WNPlatform
SOURCES        := WNSurface.cpp \
                  WNPlatformFactory.cpp \
                  XWindows/WNSurfaceXWindows.cpp \
                  XWindows/WNSurfaceManagerXWindows.cpp
ADDITIONALLIBS := $(ADDITIONALLIBS)

include ../../LibrariesHelper.mk
