include ../../../PreTestsHelper.mk

PROJECT	  := WNConcurrency
SOURCES   := Main.cpp \
             Tests/WNAtomicTests.cpp \
			 Tests/WNThreadTests.cpp \
			 Tests/WNThreadPoolTests.cpp
WNLIBS    := WNEntryPoint WNUtils
PCHFILES  := Common.h


include ../../../TestsHelper.mk

