include ../../../PreTestsHelper.mk

PROJECT	:= WNConcurrency
SOURCES := Main.cpp \
           Tests/WNMutexTests.cpp \
           Tests/WNSemaphoreTests.cpp \
           Tests/WNThreadTests.cpp \
           Tests/WNThreadPoolTests.cpp
WNLIBS := WNEntryPoint WNUtils
PCHFILES := Common.h

include ../../../TestsHelper.mk