name: Set up GCS for sccache
inputs:
  bucket:
    required: true
    type: string
  key:
    required: true
    type: string
  key-location:
    required: false
    default: ${{runner.temp}}
    type: string
  write:
    required: false
    default: false
    type: boolean
runs:
  using: composite
  steps:
    - name: Set up key file and sccache environment
      shell: bash
      run: |
        KEY_PATH="$KEY_LOCATION/gcs_key.json"
        echo "$KEY" > "$KEY_PATH"
        echo "SCCACHE_GCS_BUCKET=$BUCKET" >> $GITHUB_ENV
        echo "SCCACHE_GCS_KEY_PATH=$KEY_PATH" >> $GITHUB_ENV
        RW_MODE=$(
          [ "$INPUTS_WRITE" == 'true' ] &&
          echo 'READ_WRITE' ||
          echo 'READ_ONLY'
        )
        echo "SCCACHE_GCS_RW_MODE=$RW_MODE" >> $GITHUB_ENV
        echo "SCCACHE_IGNORE_SERVER_IO_ERROR=1" >> $GITHUB_ENV
      env:
        WRITE: ${{inputs.write}}
        KEY_LOCATION: ${{inputs.key-location}}
        BUCKET: ${{inputs.gcs-bucket}}
        KEY: ${{inputs.gcs-key}}
