include ../../../PreTestsHelper.mk

PROJECT   := WNPlatform
SOURCES   := Main.cpp \
             Tests/WNSystemTests.cpp \
			 Tests/WNTimeTests.cpp
WNLIBS    := WNPlatform	WNEntryPoint WNUtils
PCHFILES  := Common.h

include ../../../TestsHelper.mk

