include ../../../PreTestsHelper.mk

PROJECT	  := WNLogging
SOURCES   := Main.cpp \
			 Tests/WNFileLogTests.cpp \
			 Tests/WNLogTypeTests.cpp
PCHFILES  := Common.h
WNLIBS    := WNEntryPoint WNUtils


include ../../../TestsHelper.mk

