SHELL=/bin/sh
CXX?=g++
AR?=ar
INCLUDES := $(INCLUDES) -I. -I../.. -I../../../Libraries/
TARGET ?= Release
SOURCEDIR=../src/
OBJDIR = ../build/
BINDIR ?= ../../bin/
WNLIBDIR = ../../../Libraries/bin/$(TARGET)/
DEPENDENCYDIR = ../../../Externals/bin/Linux/$(shell uname -m)/$(TARGET)/
