include(CheckSymbolExists)
include(CheckIncludeFile)

macro(wn_check_include_file)
if (WN_OVERLAY_IS_ENABLED AND NOT WN_DISABLE_CXX)
  check_include_file(${ARGN})
endif()
endmacro()

macro(wn_check_include_file_cxx)
  if (WN_OVERLAY_IS_ENABLED AND NOT WN_DISABLE_CXX)
    check_include_file_cxx(${ARGN})
  endif()
endmacro()

macro(wn_check_cxx_source_compiles SOURCE VAR)
  if (WN_OVERLAY_IS_ENABLED AND NOT WN_DISABLE_CXX)
    check_cxx_source_compiles("${SOURCE}" ${VAR})
  endif()
endmacro()

macro(wn_check_symbol_exists)
if (WN_OVERLAY_IS_ENABLED AND NOT WN_DISABLE_CXX)
  check_symbol_exists(${ARGN})
endif()
endmacro()

macro(wn_fail_bad_symbol)
if (WN_OVERLAY_IS_ENABLED AND NOT WN_DISABLE_CXX)
  message(FATAL_ERROR ${ARGN})
endif()
endmacro()