function(expand_list OUTPUT PREFIX POSTFIX SEPARATOR ${ARGN})
  set(out)
  set(first ON)
  foreach(element ${ARGN})
    if(NOT first)
      set(out "${out}${SEPARATOR}")
    endif()
    set(first OFF)
    set(out "${out}${PREFIX}${element}${POSTFIX}")
  endforeach()
  set(${OUTPUT} ${out} PARENT_SCOPE)
endfunction()
