WN_BUILD_HELPER_ROOT:=../../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../../
WN_LIBRARIES:=WNGraphics WNPlatform WNEntryPoint
WN_SOURCES := ../../src/Main.cpp
PROJECT_NAME := WNGraphicsTest
PROGRAM_NAME := WNGraphicsTest
LIB_NAME := WNGraphicsTest
ACTIVITY_NAME := WNGraphicsTest
PACKAGE_NAME := org.WNProject.WNGraphicsTest
WN_ADDITIONAL_ANDROID_LIBS:=android_native_app_glue googletest_static
WN_ADDITIONAL_ANDROID_MODULES:=android/native_app_glue third_party/googletest

include $(WN_BUILD_HELPER_ROOT)Makefile
