WN_BUILD_HELPER_ROOT:=../../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../../../
WN_LIBRARIES:=WNGraphics WNPlatform WNEntryPoint
WN_SOURCES := ../../src/Main.cpp
PROJECT_NAME := WNGraphicsTest
PROGRAM_NAME := WNGraphicsTest
LIB_NAME := WNGraphicsTest
ACTIVITY_NAME := WNGraphicsTest
PACKAGE_NAME := org.WNProject.WNGraphicsTest

include $(WN_BUILD_HELPER_ROOT)Makefile
