WN_BUILD_HELPER_ROOT:=../../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../../
WN_LIBRARIES:=WNEntryPoint WNLogging
WN_SOURCES := ../../src/Main.cpp ../../src/Tests/WNFileLogTests.cpp ../../src/Tests/WNLogTypeTests.cpp
PROJECT_NAME := WNLoggingTest
PROGRAM_NAME := WNLoggingTest
LIB_NAME := WNLoggingTest
ACTIVITY_NAME := WNLoggingTest
PACKAGE_NAME := org.WNProject.WNLoggingTest
WN_ADDITIONAL_ANDROID_LIBS:=android_native_app_glue googletest_static
WN_ADDITIONAL_ANDROID_MODULES:=android/native_app_glue third_party/googletest

include $(WN_BUILD_HELPER_ROOT)Makefile
