WN_BUILD_HELPER_ROOT:=../../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../../../
WN_LIBRARIES:=gtest WNEntryPoint WNLogging
WN_SOURCES := ../../src/Main.cpp ../../src/Tests/WNFileLogTests.cpp ../../src/Tests/WNLogTypeTests.cpp
PROJECT_NAME := WNLoggingTest
PROGRAM_NAME := WNLoggingTest
LIB_NAME := WNLoggingTest
ACTIVITY_NAME := WNLoggingTest
PACKAGE_NAME := org.WNProject.WNLoggingTest

include $(WN_BUILD_HELPER_ROOT)Makefile
