WN_BUILD_HELPER_ROOT:=../../../../../Utilities/AndroidBuild/
WN_PROJECT_PATH:=../../../../../../
WN_LIBRARIES:=WNFileSystem gtest WNEntryPoint
WN_SOURCES := ../../src/Main.cpp
PROJECT_NAME := WNFileSystemTest
PROGRAM_NAME := WNFileSystemTest
LIB_NAME := WNFileSystemTest
ACTIVITY_NAME := WNFileSystemTest
PACKAGE_NAME := org.WNProject.WNFileSystemTest

include $(WN_BUILD_HELPER_ROOT)Makefile
