name: Push
on:
  push:
    branches: master
concurrency: push
permissions:
  contents: read
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      use-sccache: ${{github.actor != 'dependabot[bot]'}}
      sccache-write: true
