name: Push
on:
  push:
    branches: master
concurrency: push
permissions:
  contents: read
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      run-build: true
      run-check-licenses: true
      run-format-check-c-cpp: true
      run-format-check-md: true
