name: Update license
on:
  push:
    branches: master
    paths: .github/workflows/update-license.yml
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:
env:
  BRANCH: auto/update-license
  REGEX: ^(((\/\/|#) )?Copyright \(c\) )[0-9]{4}(, WNProject Authors(\. All rights reserved.)?)$
jobs:
  update-license:
    name: Update license
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Determine year
        id: year
        run: echo "::set-output name=value::$(date +%Y)"
      - name: Switch to '${{env.BRANCH}}'
        run: |
          git fetch origin +refs/heads/$BRANCH:refs/heads/$BRANCH || true
          git checkout $BRANCH || git checkout -b $BRANCH
      - name: Update license
        run: >
          find . -type f -not -path './.git/*' -and
          -iregex '^.*\(\.\(h\|c\|cpp\|inl\|h\.in\|s\|py\|wns\)\|LICENSE\)$'
          -exec sed -i -E "s/$REGEX/\1${{steps.year.outputs.value}}\4/" {} \;
      - name: Check for changes
        id: changes
        run: git diff --exit-code || echo '::set-output name=exist::true'
      - name: Create commit
        if: steps.changes.outputs.exist
        run: |
          git reset --hard origin/master
          find . -type f -not -path './.git/*' -and \
          -iregex '^.*\(\.\(h\|c\|cpp\|inl\|h\.in\|s\|py\|wns\)\|LICENSE\)$' \
          -exec sed -i -E "s/$REGEX/\1${{steps.year.outputs.value}}\4/" {} \;
          git config user.name $COMMIT_USERNAME
          git config user.email $COMMIT_EMAIL
          git add -u
          git commit -m 'Update license year to ${{steps.year.outputs.value}}'
          git push --force origin $BRANCH
        env:
          COMMIT_USERNAME: ${{secrets.UPDATE_LICENSE_USER}}
          COMMIT_EMAIL: ${{secrets.UPDATE_LICENSE_EMAIL}}
      - name: Create pull request
        if: steps.changes.outputs.exist
        uses: actions/github-script@v5
        with:
          script: |
            const [owner, repo] = '${{github.repository}}'.split('/');
            const base = 'refs/heads/master';
            const head = 'refs/heads/${{env.BRANCH}}';
            const labels = ['auto'];
            const title = 'Update license year to ${{steps.year.outputs.value}}';
            const pullRequests = await github.rest.pulls.list({
              head: `${owner}:${head}`,
              owner, repo, base
            });
            if (pullRequests.data.length === 0) {
              const createResult = await github.rest.pulls.create({
                title, owner, repo, head, base
              });
              github.rest.issues.addLabels({
                issue_number: createResult.data.number,
                owner, repo, labels
              });
              console.log('Created new pull request');
              return createResult.data.number;
            } else {
              const prNumber = pullRequests.data[0].number;
              github.rest.issues.update({
                issue_number: prNumber,
                title, owner, repo, labels
              });
              console.log(`Pull request already exists, updated #${prNumber}`);
              return prNumber;
            }
          result-encoding: string
          github-token: ${{secrets.UPDATE_LICENSE_TOKEN}}
