name: Validate formatting
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  validate-code-formatting-c-cpp:
    name: Validate code formatting (C/C++)
    runs-on: ubuntu-latest
    container: ghcr.io/wnproject/clang-format
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.3
      - name: Check code format
        run: >
          find . -type f
          -iregex '^.*\.\(c\|cpp\|h\|hpp\)$' -and -not
          -iregex '^\.\/\(externals\|build.*\).*$' |
          xargs clang-format --dry-run --Werror --verbose
