////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                            //
//                                                         WNProject                                                          //
//                                                                                                                            //
//         This file is distributed under the BSD 2-Clause open source license. See Licenses/License.txt for details.         //
//                                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

eWNOK,
eWNError,
eWNInvalidParameters,
eWNOutOfRange,
eWNBadType,
eWNDoesNotExist,
eWNPlatformError,
eWNReInitialized,
eWNUninitialized,
eWNInvalidFile,
