////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                            //
//                                                         WNProject                                                          //
//                                                                                                                            //
//         This file is distributed under the BSD 2-Clause open source license. See Licenses/License.txt for details.         //
//                                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

ok,
error,
invalid_parameters,
eWNOutOfRange,
eWNBadType,
eWNDoesNotExist,
eWNPlatformError,
already_initialized,
uninitialized,
eWNInvalidFile,
